# Generated by Django 3.2.12 on 2022-02-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bumpers', '0002_alter_bumper_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bumper',
            new_name='Bumpers',
        ),
    ]
